FROM clickhouse/clickhouse-server:26.3.10.60@sha256:92098d3b31dd01ba7d176faa3278d3577de9e32d847cd4b840dae8087b8d35b4

LABEL org.opencontainers.image.source="https://github.com/ClickHouse/ClickHouse"
LABEL org.opencontainers.image.version="26.3.10.60-lts"
LABEL io.kungfu.upstream.image="clickhouse/clickhouse-server:26.3.10.60"
LABEL io.kungfu.upstream.digest="sha256:92098d3b31dd01ba7d176faa3278d3577de9e32d847cd4b840dae8087b8d35b4"
